name: Deploy Web to Firebase Hosting

on:
  push:
    branches: [ "main" ]
    paths:
      - "apps/web/**"
      - "firebase.json"
      - ".firebaserc"
      - ".github/workflows/firebase-hosting.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (skip postinstall)
        run: npm install --ignore-scripts --no-audit --no-fund

      - name: Build web
        run: npm --workspace apps/web run build

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "family-bot-33940"
          channelId: "live"
