name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "firebase/**"
      - "firebase.json"
      - ".firebaserc"
      - ".github/workflows/firebase-functions.yml"

jobs:
  build-and-deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (skip postinstall)
        run: npm install --ignore-scripts --no-audit --no-fund

      - name: Build functions (TypeScript → JS)
        run: npm --workspace firebase run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $GOOGLE_APPLICATION_CREDENTIALS
          firebase deploy --only functions --project family-bot-33940 --force
